# This is the Secret for the Stateful database password which is encoded by Base64
#
# Created by Lovekush Kumar (3163193) for NAGP Assignment of DevOps and Kubernetes Advance

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_PASSWORD: MTIzNDU=  # Base64-encoded password
