#This is the Headless service for the Stateful database
#
# Created by Lovekush Kumar (3163193) for NAGP Assignment of DevOps and Kubernetes Advance
apiVersion: v1
kind: Service
metadata:
 name: database-headless-service
spec:
    ports:
    - port: 80
    selector:
        app: database
    clusterIP: None         # No Cluster IP for Headless service